# -*- coding: utf-8 -*-
"""TEST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kOOTALbdYp1Iepy5PZ-uc9UUhLm2frY
"""

i=0
for i in range(5):
    print("Hello world!")
print('This is for ISEC323')